import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getTenantId } from '@/lib/db/tenant'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const tenantId = await getTenantId()
    const { sourceMonth, targetMonth } = await request.json() as {
      sourceMonth: string
      targetMonth: string
    }

    if (!sourceMonth || !targetMonth) {
      return NextResponse.json({ error: 'sourceMonth and targetMonth are required' }, { status: 400 })
    }

    // Check if target month already has items
    const { data: existing, error: checkError } = await supabase
      .from('monthly_overheads')
      .select('id')
      .eq('tenant_id', tenantId)
      .eq('month', targetMonth)
      .limit(1)

    if (checkError) return NextResponse.json({ error: checkError.message }, { status: 500 })
    if (existing && existing.length > 0) {
      return NextResponse.json(
        { error: `${targetMonth} already has overhead items. Delete them first or edit directly.` },
        { status: 409 }
      )
    }

    // Fetch source items
    const { data: sourceItems, error: fetchError } = await supabase
      .from('monthly_overheads')
      .select('category, name, amount')
      .eq('tenant_id', tenantId)
      .eq('month', sourceMonth)

    if (fetchError) return NextResponse.json({ error: fetchError.message }, { status: 500 })
    if (!sourceItems || sourceItems.length === 0) {
      return NextResponse.json({ error: `No overheads found for ${sourceMonth}` }, { status: 404 })
    }

    // Insert copies for target month (new UUIDs auto-generated by DB)
    const copies = sourceItems.map(item => ({
      tenant_id: tenantId,
      month: targetMonth,
      category: item.category,
      name: item.name,
      amount: item.amount,
    }))

    const { data, error: insertError } = await supabase
      .from('monthly_overheads')
      .insert(copies)
      .select()

    if (insertError) return NextResponse.json({ error: insertError.message }, { status: 500 })

    const total = (data ?? []).reduce((sum, row) => sum + Number(row.amount), 0)
    return NextResponse.json({ overheads: data ?? [], total })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    if (message === 'Unauthorized') return NextResponse.json({ error: message }, { status: 401 })
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
